server:
  appversion:        "1.0.0"
  port:              ":5000"
  pprofport:         ":5555"
  mode:              "Development"
  jwtsecretkey:      "secretkey"
  cookiename:        "jwt-token"
  readtimeout:       5
  writetimeout:      5
  ssl:               false
  ctxdefaulttimeout: 12
  csrf:              false
  debug:             false

postgres:
  host:     "localhost"
  port:     "5432"
  user:     "spacedevs_user"
  password: "Spacedevs123456"
  db:       "spacedevs"
  sslmode:  false
  driver:   "pgx"

redis:
  addr:         "localhost:6379"
  password:     ""
  db:           0
  minidleconns: 200
  poolsize:     12000
  pooltimeout:  240
