server:
  appversion:        "1.0.0"
  port:              ":5000"
  pprofport:         ":5555"
  mode:              "Production"
  jwtsecretkey:      ""
  cookiename:        "jwt-token"
  readtimeout:       5s
  writetimeout:      5s
  ssl:               false
  ctxdefaulttimeout: 12s
  csrf:              false
  debug:             false

postgres:
  host:     "postgresql"
  port:     "5432"
  user:     ""
  password: ""
  db:       "spacedevs"
  sslmode:  false
  driver:   "pgx"

redis:
  addr:         "redis:6379"
  password:     ""
  db:           0
  minidleconns: 200
  poolsize:     12000
  pooltimeout:  240
