server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgresql:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: spacedevs_user
  PostgresqlPassword: Spacedevs123456
  PostgresqlDbname: spacedevs
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0